FROM python:3

ENV PYTHONUNBUFFERED 1

RUN mkdir /Ading
ADD . /Ading

WORKDIR /Ading
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python" ,"manage.py" "runserver" ]
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "BE.wsgi:application"]



